services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3151:3000"
    environment:
      - NODE_ENV=production
    # Perbaiki format volumes - harus berupa list dengan dash (-)
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

networks:
  app-network:
    driver: bridge